### ISSUE TITLE
Error when running project.

### ISSUE THREAD

**Issue by ee0pdt** [godotrecipes/characterbody3d_examples#1]
There is an error when running the project for the first time:

<img width="569" alt="image" src="https://github.com/godotrecipes/characterbody3d_examples/assets/6094917/7f88b987-493c-4839-84cd-4f95398da045">

This can be fixed by correcting the names of two nodes as shown below:

<img width="774" alt="image" src="https://github.com/godotrecipes/characterbody3d_examples/assets/6094917/9aff0c57-3783-42ab-bd96-c160d584dfdc">

**Comment by cbscribe** [comment]
Thanks. This is an issue with the imported model that crept in on the conversion from 4.0 to 4.1.
